"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { appointmentWhatsApp, whatsAppHref } from "@/lib/whatsappTemplates";

type Business={id:string;name:string;slug:string;business_mode:"products"|"appointments"|"both";whatsapp:string|null};
type Service={id:string;name:string;description:string|null;price:number|string;duration_minutes:number;buffer_minutes:number;deposit_amount:number|string|null;is_active:boolean};
type Appointment={id:string;service_id:string|null;customer_name:string;customer_phone:string;starts_at:string;ends_at:string;total:number|string;payment_status:string;appointment_status:string;note:string|null;rescheduled_at:string|null;reschedule_count:number};
type Availability={id:string;weekday:number;start_time:string;end_time:string;is_active:boolean};
type Block={id:string;starts_at:string;ends_at:string;reason:string|null};

const appointmentStates=["pending","confirmed","completed","cancelled","no_show"];
const paymentStates=["awaiting_payment","receipt_uploaded","paid","rejected"];
const weekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];

export default function AppointmentManager(){
 const router=useRouter(); const supabase=createClient();
 const [business,setBusiness]=useState<Business|null>(null); const [services,setServices]=useState<Service[]>([]); const [appointments,setAppointments]=useState<Appointment[]>([]); const [availability,setAvailability]=useState<Availability[]>([]); const [blocks,setBlocks]=useState<Block[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
 const [serviceName,setServiceName]=useState(""); const [serviceDescription,setServiceDescription]=useState(""); const [price,setPrice]=useState(""); const [duration,setDuration]=useState("60"); const [buffer,setBuffer]=useState("0"); const [deposit,setDeposit]=useState("");
 const [apptService,setApptService]=useState(""); const [customerName,setCustomerName]=useState(""); const [customerPhone,setCustomerPhone]=useState(""); const [startsAt,setStartsAt]=useState(""); const [note,setNote]=useState("");
 const [availWeekday,setAvailWeekday]=useState("1"); const [availStart,setAvailStart]=useState("09:00"); const [availEnd,setAvailEnd]=useState("17:00");
 const [blockStart,setBlockStart]=useState(""); const [blockEnd,setBlockEnd]=useState(""); const [blockReason,setBlockReason]=useState("");
 const [rescheduleTimes,setRescheduleTimes]=useState<Record<string,string>>({});

 async function load(){
  setLoading(true);
  const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace("/login");return}
  const {data:b}=await supabase.from("businesses").select("id,name,slug,business_mode,whatsapp").eq("owner_id",user.id).order("created_at").limit(1).maybeSingle();
  if(!b){router.replace("/onboarding");return}
  const biz=b as Business; setBusiness(biz);
  const [{data:s},{data:a},{data:av},{data:bl}]=await Promise.all([
   supabase.from("services").select("id,name,description,price,duration_minutes,buffer_minutes,deposit_amount,is_active").eq("business_id",biz.id).order("created_at",{ascending:false}),
   supabase.from("appointments").select("id,service_id,customer_name,customer_phone,starts_at,ends_at,total,payment_status,appointment_status,note,rescheduled_at,reschedule_count").eq("business_id",biz.id).order("starts_at",{ascending:true}).limit(200),
   supabase.from("appointment_availability").select("id,weekday,start_time,end_time,is_active").eq("business_id",biz.id).order("weekday").order("start_time"),
   supabase.from("appointment_blocks").select("id,starts_at,ends_at,reason").eq("business_id",biz.id).gte("ends_at",new Date().toISOString()).order("starts_at").limit(100)
  ]);
  setServices((s||[]) as Service[]); setAppointments((a||[]) as Appointment[]); setAvailability((av||[]) as Availability[]); setBlocks((bl||[]) as Block[]); setLoading(false);
 }
 useEffect(()=>{load()},[]);

 const upcoming=useMemo(()=>appointments.filter(a=>new Date(a.starts_at)>=new Date()&&!['cancelled','completed'].includes(a.appointment_status)),[appointments]);
 const today=useMemo(()=>{const d=new Date().toDateString();return appointments.filter(a=>new Date(a.starts_at).toDateString()===d&&a.appointment_status!=="cancelled")},[appointments]);
 const awaiting=appointments.filter(a=>a.payment_status==="awaiting_payment"||a.payment_status==="receipt_uploaded").length;
 const next=upcoming[0];
 const attention=appointments.filter(a=>a.payment_status==="receipt_uploaded"||a.appointment_status==="pending").slice(0,8);

 function serviceFor(a:Appointment){return services.find(s=>s.id===a.service_id)}
 function waInput(a:Appointment){const s=serviceFor(a);return {businessName:business!.name,customerName:a.customer_name,serviceName:s?.name,startsAt:a.starts_at,total:Number(a.total),deposit:s?.deposit_amount==null?null:Number(s.deposit_amount)}}

 async function addService(e:FormEvent){e.preventDefault(); if(!business)return; setMessage(""); const p=Number(price),d=Number(duration),buf=Number(buffer); if(!serviceName.trim()||!Number.isFinite(p)||p<0||!Number.isFinite(d)||d<=0){setMessage("Enter a valid service name, price and duration.");return} const {error}=await supabase.from("services").insert({business_id:business.id,name:serviceName.trim(),description:serviceDescription.trim()||null,price:p,duration_minutes:d,buffer_minutes:Number.isFinite(buf)&&buf>=0?buf:0,deposit_amount:deposit?Number(deposit):null}); if(error){setMessage(error.message);return} setServiceName("");setServiceDescription("");setPrice("");setDuration("60");setBuffer("0");setDeposit("");await load()}
 async function toggleService(s:Service){await supabase.from("services").update({is_active:!s.is_active}).eq("id",s.id);await load()}
 async function addAppointment(e:FormEvent){e.preventDefault(); if(!business)return; const service=services.find(s=>s.id===apptService); if(!service||!customerName.trim()||!customerPhone.trim()||!startsAt){setMessage("Choose a service and complete the booking details.");return} const start=new Date(startsAt); const end=new Date(start.getTime()+service.duration_minutes*60000); const {error}=await supabase.from("appointments").insert({business_id:business.id,service_id:service.id,customer_name:customerName.trim(),customer_phone:customerPhone.trim(),starts_at:start.toISOString(),ends_at:end.toISOString(),total:Number(service.price),note:note.trim()||null}); if(error){setMessage(error.message);return} setApptService("");setCustomerName("");setCustomerPhone("");setStartsAt("");setNote("");setMessage("Appointment added.");await load()}
 async function updateAppointment(a:Appointment,field:"appointment_status"|"payment_status",value:string){const changes:any={[field]:value};if(field==="appointment_status"&&value==="cancelled")changes.cancelled_at=new Date().toISOString();if(field==="appointment_status"&&value!=="cancelled")changes.cancelled_at=null;const {error}=await supabase.from("appointments").update(changes).eq("id",a.id);setMessage(error?error.message:"Appointment updated.");await load()}
 async function addAvailability(e:FormEvent){e.preventDefault();if(!business)return;if(!availStart||!availEnd||availEnd<=availStart){setMessage("End time must be after start time.");return}const {error}=await supabase.from("appointment_availability").insert({business_id:business.id,weekday:Number(availWeekday),start_time:availStart,end_time:availEnd,is_active:true});setMessage(error?error.message:"Appointment hours added.");if(!error)await load()}
 async function toggleAvailability(a:Availability){await supabase.from("appointment_availability").update({is_active:!a.is_active}).eq("id",a.id);await load()}
 async function deleteAvailability(id:string){await supabase.from("appointment_availability").delete().eq("id",id);await load()}
 async function addBlock(e:FormEvent){e.preventDefault();if(!business)return;if(!blockStart||!blockEnd||new Date(blockEnd)<=new Date(blockStart)){setMessage("Blocked end time must be after the start time.");return}const {error}=await supabase.from("appointment_blocks").insert({business_id:business.id,starts_at:new Date(blockStart).toISOString(),ends_at:new Date(blockEnd).toISOString(),reason:blockReason.trim()||null});setMessage(error?error.message:"Time blocked.");if(!error){setBlockStart("");setBlockEnd("");setBlockReason("");await load()}}
 async function deleteBlock(id:string){await supabase.from("appointment_blocks").delete().eq("id",id);await load()}
 async function reschedule(a:Appointment){const value=rescheduleTimes[a.id];if(!value){setMessage("Choose a new date and time first.");return}const {data,error}=await supabase.functions.invoke("reschedule-appointment",{body:{appointment_id:a.id,starts_at:new Date(value).toISOString()}});if(error){setMessage(error.message);return}if((data as any)?.error){setMessage((data as any).error);return}setRescheduleTimes(v=>({...v,[a.id]:""}));setMessage("Appointment rescheduled. Use the WhatsApp button to send the updated time to the customer.");await load()}

 if(loading)return <main className="shell"><div className="card" style={{marginTop:60}}>Opening appointments…</div></main>;
 if(!business)return null;

 return <main className="shell" style={{paddingTop:32,paddingBottom:80}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",marginBottom:26,flexWrap:"wrap"}}><div><div className="eyebrow">KADAI · {business.name}</div><h1 style={{margin:"4px 0 4px"}}>Appointments</h1><p className="muted" style={{margin:0}}>Bookings, availability and customer follow-up in one place.</p></div><div style={{display:"flex",gap:10}}><Link className="btn secondary" href="/dashboard">← Dashboard</Link><Link className="btn" href={`/${business.slug}`}>View my KADAI</Link></div></div>

  <div className="metric-grid" style={{marginBottom:28}}><div className="metric"><span className="muted">Appointments today</span><b>{today.length}</b></div><div className="metric"><span className="muted">Next appointment</span><b style={{fontSize:20}}>{next?new Date(next.starts_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</b></div><div className="metric"><span className="muted">Need payment check</span><b>{awaiting}</b></div><div className="metric"><span className="muted">Upcoming</span><b>{upcoming.length}</b></div></div>

  {message&&<div className="card" style={{marginBottom:18,display:"flex",justifyContent:"space-between",gap:12}}>{message}<button style={{border:0,background:"transparent"}} onClick={()=>setMessage("")}>×</button></div>}

  <section className="section"><h2>Needs your attention</h2><div style={{display:"grid",gap:10}}>{attention.map(a=><div className="card" key={a.id} style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap"}}><div><b>{a.customer_name}</b><div className="muted">{serviceFor(a)?.name||"Service"} · {new Date(a.starts_at).toLocaleString()} · {a.payment_status.replaceAll("_"," ")}</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{a.payment_status==="awaiting_payment"&&<a className="btn secondary" target="_blank" rel="noreferrer" href={whatsAppHref(a.customer_phone,appointmentWhatsApp.paymentReminder(waInput(a)))}>Payment reminder</a>}<a className="btn secondary" target="_blank" rel="noreferrer" href={whatsAppHref(a.customer_phone,a.appointment_status==="pending"?appointmentWhatsApp.confirmed(waInput(a)):appointmentWhatsApp.reminder(waInput(a)))}>WhatsApp</a></div></div>)}{attention.length===0&&<div className="card"><b>All caught up.</b><p className="muted" style={{marginBottom:0}}>Nothing needs your attention right now.</p></div>}</div></section>

  <section className="section"><div className="eyebrow">AVAILABILITY</div><h2>When can customers book?</h2><p className="muted">If you add appointment hours, KADAI will reject requests outside those hours. Leave this empty only if you intentionally accept requests at any time.</p><div className="grid3" style={{alignItems:"start"}}><form className="card" onSubmit={addAvailability}><h3>Add appointment hours</h3><div className="field"><label>Day</label><select value={availWeekday} onChange={e=>setAvailWeekday(e.target.value)}>{weekdays.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></div><div className="field"><label>From</label><input type="time" value={availStart} onChange={e=>setAvailStart(e.target.value)} required/></div><div className="field"><label>Until</label><input type="time" value={availEnd} onChange={e=>setAvailEnd(e.target.value)} required/></div><button className="btn">Add hours</button></form><div style={{gridColumn:"span 2",display:"grid",gap:10}}>{availability.length===0?<div className="card"><b>No appointment hours set.</b><p className="muted">Bookings are currently allowed at any future time unless blocked or already occupied.</p></div>:availability.map(a=><div className="card" key={a.id} style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><b>{weekdays[a.weekday]}</b><div className="muted">{a.start_time.slice(0,5)}–{a.end_time.slice(0,5)} · {a.is_active?"Active":"Paused"}</div></div><div style={{display:"flex",gap:8}}><button className="btn secondary" onClick={()=>toggleAvailability(a)}>{a.is_active?"Pause":"Activate"}</button><button className="btn secondary" onClick={()=>deleteAvailability(a.id)}>Delete</button></div></div>)}</div></div></section>

  <section className="section"><h2>Block time off</h2><div className="grid3" style={{alignItems:"start"}}><form className="card" onSubmit={addBlock}><div className="field"><label>Starts</label><input type="datetime-local" value={blockStart} onChange={e=>setBlockStart(e.target.value)} required/></div><div className="field"><label>Ends</label><input type="datetime-local" value={blockEnd} onChange={e=>setBlockEnd(e.target.value)} required/></div><div className="field"><label>Reason</label><input value={blockReason} onChange={e=>setBlockReason(e.target.value)} placeholder="Leave, lunch, closed…"/></div><button className="btn">Block time</button></form><div style={{gridColumn:"span 2",display:"grid",gap:10}}>{blocks.length===0?<div className="card">No upcoming blocked times.</div>:blocks.map(b=><div className="card" key={b.id} style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><b>{new Date(b.starts_at).toLocaleString()} → {new Date(b.ends_at).toLocaleString()}</b><div className="muted">{b.reason||"Unavailable"}</div></div><button className="btn secondary" onClick={()=>deleteBlock(b.id)}>Remove</button></div>)}</div></div></section>

  <section className="section"><h2>Services</h2><div className="grid3" style={{alignItems:"start"}}><form className="card" onSubmit={addService}><h3>Add service</h3><div className="field"><label>Service name</label><input value={serviceName} onChange={e=>setServiceName(e.target.value)} placeholder="Bridal makeup" required/></div><div className="field"><label>Description</label><textarea rows={3} value={serviceDescription} onChange={e=>setServiceDescription(e.target.value)}/></div><div className="field"><label>Price (BND)</label><input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></div><div className="field"><label>Duration (minutes)</label><input type="number" min="5" value={duration} onChange={e=>setDuration(e.target.value)} required/></div><div className="field"><label>Buffer after appointment</label><input type="number" min="0" value={buffer} onChange={e=>setBuffer(e.target.value)}/></div><div className="field"><label>Deposit (optional, BND)</label><input type="number" min="0" step="0.01" value={deposit} onChange={e=>setDeposit(e.target.value)}/></div><button className="btn">Add service</button></form><div style={{gridColumn:"span 2",display:"grid",gap:10}}>{services.length===0?<div className="card">No services yet.</div>:services.map(s=><div className="card" key={s.id} style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center"}}><div><b>{s.name}</b><div className="muted">BND {Number(s.price).toFixed(2)} · {s.duration_minutes} min{s.buffer_minutes?` + ${s.buffer_minutes} min buffer`:""}{s.deposit_amount!=null?` · BND ${Number(s.deposit_amount).toFixed(2)} deposit`:""} · {s.is_active?"Visible":"Hidden"}</div></div><button className="btn secondary" onClick={()=>toggleService(s)}>{s.is_active?"Hide":"Show"}</button></div>)}</div></div></section>

  <section className="section"><h2>Add booking manually</h2><form className="card" onSubmit={addAppointment} style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:14}}><div className="field"><label>Service</label><select value={apptService} onChange={e=>setApptService(e.target.value)} required><option value="">Choose service</option>{services.filter(s=>s.is_active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="field"><label>Date & time</label><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} required/></div><div className="field"><label>Customer name</label><input value={customerName} onChange={e=>setCustomerName(e.target.value)} required/></div><div className="field"><label>WhatsApp number</label><input value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)} placeholder="+673 ..." required/></div><div className="field" style={{gridColumn:"1 / -1"}}><label>Notes</label><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)}/></div><div style={{gridColumn:"1 / -1"}}><button className="btn">Add appointment</button></div></form></section>

  <section className="section"><h2>Upcoming appointments</h2><div style={{display:"grid",gap:10}}>{upcoming.length===0?<div className="card">No upcoming appointments.</div>:upcoming.map(a=>{const s=serviceFor(a);return <div className="card" key={a.id} style={{display:"grid",gap:12}}><div style={{display:"grid",gridTemplateColumns:"1.4fr 1fr 1fr",gap:12,alignItems:"center"}}><div><b>{a.customer_name}</b><div className="muted">{s?.name||"Service"} · {new Date(a.starts_at).toLocaleString()} · BND {Number(a.total).toFixed(2)}{a.reschedule_count?` · rescheduled ${a.reschedule_count}×`:""}</div></div><select value={a.payment_status} onChange={e=>updateAppointment(a,"payment_status",e.target.value)}>{paymentStates.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><select value={a.appointment_status} onChange={e=>updateAppointment(a,"appointment_status",e.target.value)}>{appointmentStates.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></div><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><input type="datetime-local" value={rescheduleTimes[a.id]||""} onChange={e=>setRescheduleTimes(v=>({...v,[a.id]:e.target.value}))} style={{padding:"10px 12px",border:"1px solid #d9cbc0",borderRadius:12}}/><button className="btn secondary" onClick={()=>reschedule(a)}>Reschedule</button><a className="btn secondary" target="_blank" rel="noreferrer" href={whatsAppHref(a.customer_phone,appointmentWhatsApp.rescheduled(waInput(a)))}>Send updated time</a><a className="btn secondary" target="_blank" rel="noreferrer" href={whatsAppHref(a.customer_phone,appointmentWhatsApp.reminder(waInput(a)))}>Reminder</a></div></div>})}</div></section>
 </main>
}
