"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Business={id:string;name:string;slug:string;plan:string;description:string|null;bank_name:string|null;account_name:string|null;account_number:string|null;pickup_address:string|null;pickup_enabled:boolean;delivery_enabled:boolean};
type Product={id:string;name:string;description:string|null;price:number|string;stock_limit:number|null;is_active:boolean};
type Order={id:string;order_number:number;customer_name:string;customer_phone:string;total:number|string;fulfilment:string;payment_status:string;order_status:string;created_at:string};
type Campaign={id:string;name:string;opens_at:string|null;closes_at:string|null;collection_start:string|null;collection_end:string|null;order_limit:number|null;is_active:boolean};
type Slot={id:string;slot_date:string;label:string;fulfilment:string;capacity:number;is_active:boolean};

const orderStates=["new","confirmed","preparing","ready","completed","cancelled"];
const paymentStates=["awaiting_payment","receipt_uploaded","paid","rejected"];

export default function MerchantDashboard(){
 const router=useRouter(); const supabase=createClient();
 const [business,setBusiness]=useState<Business|null>(null); const [products,setProducts]=useState<Product[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [slots,setSlots]=useState<Slot[]>([]);
 const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
 const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [price,setPrice]=useState(""); const [stock,setStock]=useState("");
 const [campaignName,setCampaignName]=useState(""); const [campaignClose,setCampaignClose]=useState(""); const [collectionStart,setCollectionStart]=useState(""); const [collectionEnd,setCollectionEnd]=useState(""); const [campaignLimit,setCampaignLimit]=useState("");
 const [slotDate,setSlotDate]=useState(""); const [slotLabel,setSlotLabel]=useState(""); const [slotMethod,setSlotMethod]=useState("pickup"); const [slotCapacity,setSlotCapacity]=useState("");
 const [bankName,setBankName]=useState(""); const [accountName,setAccountName]=useState(""); const [accountNumber,setAccountNumber]=useState(""); const [pickupAddress,setPickupAddress]=useState(""); const [pickupEnabled,setPickupEnabled]=useState(true); const [deliveryEnabled,setDeliveryEnabled]=useState(true);

 async function load(){
  const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace("/login");return}
  const {data:b}=await supabase.from("businesses").select("id,name,slug,plan,description,bank_name,account_name,account_number,pickup_address,pickup_enabled,delivery_enabled").eq("owner_id",user.id).order("created_at").limit(1).maybeSingle();
  if(!b){router.replace("/onboarding");return}
  const biz=b as Business; setBusiness(biz); setBankName(biz.bank_name||""); setAccountName(biz.account_name||""); setAccountNumber(biz.account_number||""); setPickupAddress(biz.pickup_address||""); setPickupEnabled(biz.pickup_enabled); setDeliveryEnabled(biz.delivery_enabled);
  const [{data:p},{data:o},{data:c},{data:s}]=await Promise.all([
   supabase.from("products").select("id,name,description,price,stock_limit,is_active").eq("business_id",biz.id).order("created_at",{ascending:false}),
   supabase.from("orders").select("id,order_number,customer_name,customer_phone,total,fulfilment,payment_status,order_status,created_at").eq("business_id",biz.id).order("created_at",{ascending:false}).limit(100),
   supabase.from("preorder_campaigns").select("id,name,opens_at,closes_at,collection_start,collection_end,order_limit,is_active").eq("business_id",biz.id).order("created_at",{ascending:false}),
   supabase.from("availability_slots").select("id,slot_date,label,fulfilment,capacity,is_active").eq("business_id",biz.id).order("slot_date",{ascending:true})
  ]);
  setProducts((p||[]) as Product[]); setOrders((o||[]) as Order[]); setCampaigns((c||[]) as Campaign[]); setSlots((s||[]) as Slot[]); setLoading(false);
 }
 useEffect(()=>{load()},[]);

 const today=useMemo(()=>{const d=new Date().toDateString();return orders.filter(o=>new Date(o.created_at).toDateString()===d)},[orders]);
 const salesToday=today.reduce((s,o)=>s+Number(o.total),0); const awaiting=orders.filter(o=>o.payment_status==="awaiting_payment"||o.payment_status==="receipt_uploaded").length;
 const customers=useMemo(()=>{const m=new Map<string,{name:string;phone:string;orders:number;spent:number}>();orders.forEach(o=>{const k=o.customer_phone;const prev=m.get(k)||{name:o.customer_name,phone:o.customer_phone,orders:0,spent:0};prev.orders+=1;prev.spent+=Number(o.total);m.set(k,prev)});return [...m.values()].sort((a,b)=>b.spent-a.spent)},[orders]);

 async function addProduct(e:FormEvent){e.preventDefault(); if(!business)return; setMessage(""); const value=Number(price); if(!name.trim()||!Number.isFinite(value)||value<0){setMessage("Enter a valid product name and price.");return} const {error}=await supabase.from("products").insert({business_id:business.id,name:name.trim(),description:description.trim()||null,price:value,stock_limit:stock?Number(stock):null}); if(error){setMessage(error.message);return} setName("");setDescription("");setPrice("");setStock("");await load()}
 async function toggleProduct(p:Product){await supabase.from("products").update({is_active:!p.is_active}).eq("id",p.id);await load()}
 async function updateOrder(id:string,field:"order_status"|"payment_status",value:string){await supabase.from("orders").update({[field]:value}).eq("id",id);await load()}
 async function addCampaign(e:FormEvent){e.preventDefault();if(!business||business.plan==="free")return;const {error}=await supabase.from("preorder_campaigns").insert({business_id:business.id,name:campaignName.trim(),closes_at:campaignClose?new Date(campaignClose).toISOString():null,collection_start:collectionStart||null,collection_end:collectionEnd||null,order_limit:campaignLimit?Number(campaignLimit):null,is_active:true});if(error){setMessage(error.message);return}setCampaignName("");setCampaignClose("");setCollectionStart("");setCollectionEnd("");setCampaignLimit("");await load()}
 async function toggleCampaign(c:Campaign){if(!business||business.plan==="free")return;await supabase.from("preorder_campaigns").update({is_active:!c.is_active}).eq("id",c.id);await load()}
 async function addSlot(e:FormEvent){e.preventDefault();if(!business||business.plan==="free")return;const cap=Number(slotCapacity);if(!slotDate||!slotLabel.trim()||!Number.isFinite(cap)||cap<0)return;const {error}=await supabase.from("availability_slots").insert({business_id:business.id,slot_date:slotDate,label:slotLabel.trim(),fulfilment:slotMethod,capacity:cap});if(error){setMessage(error.message);return}setSlotDate("");setSlotLabel("");setSlotCapacity("");await load()}
 async function toggleSlot(s:Slot){if(!business||business.plan==="free")return;await supabase.from("availability_slots").update({is_active:!s.is_active}).eq("id",s.id);await load()}
 async function saveSettings(e:FormEvent){e.preventDefault();if(!business)return;const {error}=await supabase.from("businesses").update({bank_name:bankName.trim()||null,account_name:accountName.trim()||null,account_number:accountNumber.trim()||null,pickup_address:pickupAddress.trim()||null,pickup_enabled:pickupEnabled,delivery_enabled:deliveryEnabled}).eq("id",business.id);setMessage(error?error.message:"Settings saved.");await load()}
 async function signOut(){await supabase.auth.signOut();router.push("/login")}
 if(loading)return <main className="shell"><div className="card" style={{marginTop:60}}>Opening your KADAI…</div></main>;
 if(!business)return null;
 const advanced=business.plan!=="free";
 return <div className="dashboard"><aside className="sidebar"><div style={{marginBottom:30}}><div className="brand">KADAI</div><div className="muted" style={{fontSize:11}}>by IZIRA</div></div><a className="active" href="#overview">Home</a><a href="#orders">Orders</a><a href="#products">Products</a><a href="#preorders">Preorders{!advanced?" · Locked":""}</a><a href="#availability">Calendar{!advanced?" · Locked":""}</a><a href="#customers">Customers</a><a href="#settings">Store</a><Link href="/dashboard/plan">Money & plan</Link><div style={{marginTop:30}}><Link href={`/${business.slug}`}>View my KADAI →</Link></div><button className="btn" style={{marginTop:18}} onClick={signOut}>Sign out</button></aside><main className="main" id="overview"><div className="eyebrow">{business.name} · {business.plan}</div><h1 style={{fontSize:42,margin:"6px 0 26px"}}>What’s happening today?</h1><div className="metric-grid"><div className="metric"><span className="muted">Orders today</span><b>{today.length}</b></div><div className="metric"><span className="muted">Sales today</span><b>BND {salesToday.toFixed(2)}</b></div><div className="metric"><span className="muted">Need payment check</span><b>{awaiting}</b></div><div className="metric"><span className="muted">Customers</span><b>{customers.length}</b></div></div>
 <section id="orders" className="section"><h2>Orders</h2>{orders.length===0?<div className="card"><b>No orders yet.</b><p className="muted">Share izira.xyz/{business.slug} when your KADAI is ready.</p></div>:<div style={{display:"grid",gap:10}}>{orders.map(o=><div className="card" key={o.id} style={{display:"grid",gridTemplateColumns:"1fr 1fr 140px 160px",gap:12,alignItems:"center"}}><div><b>#{o.order_number} · {o.customer_name}</b><div className="muted">{o.customer_phone} · {o.fulfilment} · BND {Number(o.total).toFixed(2)}</div></div><select value={o.payment_status} onChange={e=>updateOrder(o.id,"payment_status",e.target.value)}>{paymentStates.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><select value={o.order_status} onChange={e=>updateOrder(o.id,"order_status",e.target.value)}>{orderStates.map(x=><option key={x} value={x}>{x}</option>)}</select><span className="muted">{new Date(o.created_at).toLocaleDateString()}</span></div>)}</div>}</section>
 <section id="products" className="section"><h2>Products</h2><div className="grid3" style={{alignItems:"start"}}><form className="card" onSubmit={addProduct}><h3>Add product</h3><div className="field"><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label>Description</label><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="field"><label>Price (BND)</label><input type="number" step="0.01" min="0" value={price} onChange={e=>setPrice(e.target.value)} required/></div><div className="field"><label>How many can you sell?</label><input type="number" min="0" value={stock} onChange={e=>setStock(e.target.value)} placeholder="Optional"/></div><button className="btn">Add product</button></form><div style={{gridColumn:"span 2",display:"grid",gap:12}}>{products.length===0?<div className="card">No products yet.</div>:products.map(p=><div className="card" key={p.id} style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center"}}><div><b>{p.name}</b><div className="muted">BND {Number(p.price).toFixed(2)} · {p.stock_limit==null?"No limit":`${p.stock_limit} max`} · {p.is_active?"Visible":"Hidden"}</div></div><button className="btn secondary" onClick={()=>toggleProduct(p)}>{p.is_active?"Hide":"Show"}</button></div>)}</div></div></section>
 <section id="preorders" className="section"><h2>Preorders</h2>{!advanced?<div className="card"><div className="eyebrow">STARTER FEATURE</div><h3>Open a preorder without the chat chaos</h3><p className="muted">Set collection dates, order caps and a closing time. KADAI keeps the limits for you.</p><Link href="/dashboard/plan" className="btn">View plans</Link></div>:<div className="grid3" style={{alignItems:"start"}}><form className="card" onSubmit={addCampaign}><div className="field"><label>Preorder name</label><input value={campaignName} onChange={e=>setCampaignName(e.target.value)} placeholder="Hari Raya Cookies 2027" required/></div><div className="field"><label>Orders close</label><input type="datetime-local" value={campaignClose} onChange={e=>setCampaignClose(e.target.value)}/></div><div className="field"><label>Collection starts</label><input type="date" value={collectionStart} onChange={e=>setCollectionStart(e.target.value)}/></div><div className="field"><label>Collection ends</label><input type="date" value={collectionEnd} onChange={e=>setCollectionEnd(e.target.value)}/></div><div className="field"><label>Maximum orders</label><input type="number" min="0" value={campaignLimit} onChange={e=>setCampaignLimit(e.target.value)} placeholder="Optional"/></div><button className="btn">Open preorder</button></form><div style={{gridColumn:"span 2",display:"grid",gap:12}}>{campaigns.length===0?<div className="card">No preorders yet.</div>:campaigns.map(c=><div className="card" key={c.id}><div style={{display:"flex",justifyContent:"space-between",gap:20}}><div><b>{c.name}</b><div className="muted">{c.collection_start||"No collection start"}{c.collection_end?` → ${c.collection_end}`:""} · {c.order_limit?`${c.order_limit} order cap`:"No cap"}</div></div><button className="btn secondary" onClick={()=>toggleCampaign(c)}>{c.is_active?"Pause":"Open"}</button></div></div>)}</div></div>}</section>
 <section id="availability" className="section"><h2>Calendar & capacity</h2>{!advanced?<div className="card"><div className="eyebrow">STARTER FEATURE</div><h3>No more “masih ada slot?”</h3><p className="muted">Set how many orders you can handle for a date or pickup/delivery slot. KADAI stops new orders when you are full.</p><Link href="/dashboard/plan" className="btn">View plans</Link></div>:<div className="grid3" style={{alignItems:"start"}}><form className="card" onSubmit={addSlot}><div className="field"><label>Date</label><input type="date" value={slotDate} onChange={e=>setSlotDate(e.target.value)} required/></div><div className="field"><label>Time / label</label><input value={slotLabel} onChange={e=>setSlotLabel(e.target.value)} placeholder="4–6 PM" required/></div><div className="field"><label>Pickup or delivery?</label><select value={slotMethod} onChange={e=>setSlotMethod(e.target.value)}><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select></div><div className="field"><label>How many orders can you take?</label><input type="number" min="0" value={slotCapacity} onChange={e=>setSlotCapacity(e.target.value)} required/></div><button className="btn">Add slot</button></form><div style={{gridColumn:"span 2",display:"grid",gap:12}}>{slots.length===0?<div className="card">No slots yet.</div>:slots.map(s=><div className="card" key={s.id} style={{display:"flex",justifyContent:"space-between",gap:20}}><div><b>{s.slot_date} · {s.label}</b><div className="muted">{s.fulfilment} · {s.capacity} order capacity · {s.is_active?"Open":"Closed"}</div></div><button className="btn secondary" onClick={()=>toggleSlot(s)}>{s.is_active?"Close":"Open"}</button></div>)}</div></div>}</section>
 <section id="customers" className="section"><h2>Customers</h2>{customers.length===0?<div className="card">Customer history will appear after your first order.</div>:<div className="table"><div className="tr head"><span>Customer</span><span>Phone</span><span>Orders</span><span>Spent</span><span></span></div>{customers.map(c=><div className="tr" key={c.phone}><span><b>{c.name}</b></span><span>{c.phone}</span><span>{c.orders}</span><span>BND {c.spent.toFixed(2)}</span><span></span></div>)}</div>}</section>
 <section id="settings" className="section"><h2>Store</h2><form className="card" onSubmit={saveSettings} style={{maxWidth:760}}><div className="grid3"><div className="field"><label>Bank</label><input value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="BIBD"/></div><div className="field"><label>Account name</label><input value={accountName} onChange={e=>setAccountName(e.target.value)}/></div><div className="field"><label>Account number</label><input value={accountNumber} onChange={e=>setAccountNumber(e.target.value)}/></div></div><div className="field" style={{marginTop:12}}><label>Pickup address / instructions</label><textarea rows={3} value={pickupAddress} onChange={e=>setPickupAddress(e.target.value)}/></div><div style={{display:"flex",gap:18,margin:"16px 0"}}><label><input type="checkbox" checked={pickupEnabled} onChange={e=>setPickupEnabled(e.target.checked)}/> Pickup is open</label><label><input type="checkbox" checked={deliveryEnabled} onChange={e=>setDeliveryEnabled(e.target.checked)}/> Delivery is open</label></div>{message&&<p>{message}</p>}<button className="btn">Save</button></form></section>
 </main></div>
}
