import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "./nav";
import { createClient } from "./supabase";

const reserved=new Set(["kadai","dashboard","login","signup","pricing","about","admin","api","onboarding","support","settings","orders","products","customers","checkout","auth","terms","privacy","appointments","services"]);
type BusinessMode="products"|"appointments"|"both";
function normaliseSlug(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,40)}

export default function OnboardingForm(){
 const router=useRouter();const supabase=createClient();
 const [name,setName]=useState("");const [slug,setSlug]=useState("");const [description,setDescription]=useState("");const [whatsapp,setWhatsapp]=useState("");const [businessMode,setBusinessMode]=useState<BusinessMode>("products");const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");const clean=useMemo(()=>normaliseSlug(slug||name),[slug,name]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login");return}if(clean.length<3){setMessage("Your KADAI link must be at least 3 characters.");setLoading(false);return}if(reserved.has(clean)){setMessage("That KADAI link is reserved. Try another one.");setLoading(false);return}const {data:existing}=await supabase.from("businesses").select("id").eq("slug",clean).maybeSingle();if(existing){setMessage("That KADAI link is already taken.");setLoading(false);return}const {error}=await supabase.from("businesses").insert({owner_id:user.id,name:name.trim(),slug:clean,description:description.trim()||null,whatsapp:whatsapp.trim()||null,business_mode:businessMode});if(error){setMessage(error.message);setLoading(false);return}router.push(businessMode==="products"?"/dashboard":"/dashboard/appointments");router.refresh()}
 const modes:[BusinessMode,string,string][]=[["products","Products","I sell physical products, food, gifts or preorders."],["appointments","Appointments / Services","Customers book my time or a service."],["both","Both","I sell products and also take appointments."]];
 return <form onSubmit={submit} className="card" style={{maxWidth:700,margin:"50px auto",padding:28}}><div style={{marginBottom:24}}><div style={{fontSize:30,fontWeight:900,letterSpacing:"-.04em",lineHeight:1}}>KADAI</div><div className="muted" style={{fontSize:12,marginTop:4}}>by IZIRA</div></div><div className="eyebrow">BUKA KADAI</div><h1>Let’s set up your kadai.</h1><p className="muted">Tell us how you sell. KADAI will shape the workspace around your business.</p><div className="field"><label>How do you sell?</label><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:10}}>{modes.map(([value,title,copy])=><button key={value} type="button" onClick={()=>setBusinessMode(value)} className="card" style={{textAlign:"left",padding:14,border:businessMode===value?"2px solid #a65f46":"1px solid rgba(0,0,0,.12)",background:businessMode===value?"#f5e8df":"white",cursor:"pointer"}}><b>{title}</b><div className="muted" style={{fontSize:12,marginTop:5}}>{copy}</div></button>)}</div></div><div className="field"><label>Business name</label><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Aisyah Bakery"/></div><div className="field"><label>Your KADAI link</label><div style={{display:"flex",alignItems:"center",gap:8}}><span className="muted">izira.xyz/</span><input required value={slug} onChange={e=>setSlug(normaliseSlug(e.target.value))} placeholder={normaliseSlug(name)||"aisyahbakery"}/></div><div className="muted" style={{fontSize:13,marginTop:6}}>Customers will visit: izira.xyz/{clean||"yourstore"}</div></div><div className="field"><label>Tell customers about your business</label><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder={businessMode==="appointments"?"Home-based makeup artist · By appointment only":"Fresh bakes made to order · Preorder only"}/></div><div className="field"><label>WhatsApp number</label><input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} placeholder="+673 ..."/><div className="muted" style={{fontSize:12,marginTop:6}}>KADAI will use this for customer-to-seller WhatsApp actions.</div></div>{message&&<div className="card" style={{padding:12,marginBottom:14}}>{message}</div>}<button className="btn" disabled={loading}>{loading?"Opening your KADAI…":"Buka Kadai"}</button><p className="muted" style={{fontSize:12,marginTop:14}}>Buka Kadai. Start Jual.</p></form>
}
