-- IZIRA Solutions shared WhatsApp support router.
-- Corporate support data stays separate from KADAI and myPOV product data.

create table if not exists public.whatsapp_support_conversations (
  customer_phone text primary key,
  selected_team text check (selected_team in ('kadai','mypov','izira_solutions')),
  first_message_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  routed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '24 hours'),
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_support_messages (
  id bigint generated by default as identity primary key,
  meta_message_id text unique,
  customer_phone text not null,
  direction text not null check (direction in ('inbound','outbound')),
  message_type text not null,
  body text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists whatsapp_support_messages_phone_created_idx
  on public.whatsapp_support_messages (customer_phone, created_at desc);

alter table public.whatsapp_support_conversations enable row level security;
alter table public.whatsapp_support_messages enable row level security;

-- No anon/authenticated policies are intentionally created.
-- The Edge Function uses the service-role key and Meta webhook signature verification.
