import Link from "next/link";

const plans=[
 {name:"Free",price:"BND 0",sub:"A useful KADAI from day one — not just a demo.",features:["30 orders/month","Unlimited products & services","Products, appointments or both","Today + Needs Attention","Basic customer history","Basic sales summary","1 active preorder campaign","Basic capacity slots","Manual WhatsApp actions","Bank transfer + receipt upload","Powered by KADAI attribution"],cta:"Buka Kadai",href:"/signup"},
 {name:"Starter",price:"BND 8/month",sub:"For active microbusinesses that need more room and automation.",features:["150 orders/month","Everything in Free","Unlimited preorder campaigns","Advanced date/time capacity","Richer customer history","Sales dashboard & forecast","Reminder/automation features as available","More storefront controls"],cta:"Buka Kadai",href:"/signup",note:"Upgrade manually when ready"},
 {name:"Pro",price:"BND 18/month",sub:"For growing sellers who want fewer limits and more control.",features:["Unlimited orders","Everything in Starter","Custom domain entitlement","Remove KADAI attribution","Advanced controls & automation","Exports","Deeper analytics","2–3 staff accounts later"],cta:"Buka Kadai",href:"/signup",note:"Upgrade manually when ready"}
];

export default function PricingPage(){
 return <main className="shell" style={{paddingBottom:70}}>
  <nav className="nav"><Link href="/kadai" style={{textDecoration:"none"}}><div style={{fontSize:26,fontWeight:900,letterSpacing:"-.04em",lineHeight:1}}>KADAI</div><div className="muted" style={{fontSize:11,marginTop:3}}>by IZIRA</div></Link><div className="navlinks"><Link href="/login">Sign in</Link><Link href="/signup" className="pill">Buka Kadai</Link></div></nav>
  <section style={{textAlign:"center",padding:"48px 0 36px"}}><div className="eyebrow">SIMPLE PRICING</div><h1 style={{fontSize:"clamp(42px,7vw,72px)",letterSpacing:"-.05em",margin:"12px 0"}}>Free should still feel useful.</h1><p className="muted" style={{fontSize:19,maxWidth:720,margin:"0 auto"}}>Start with real selling, booking, preorder and capacity tools. Upgrade when your business needs more scale, automation and control.</p></section>
  <section className="grid3" style={{alignItems:"stretch"}}>{plans.map((p,i)=><article className="card" key={p.name} style={{padding:28,display:"flex",flexDirection:"column",gap:18,border:i===1?"2px solid #b96545":undefined}}><div>{i===1&&<div className="eyebrow">MOST FLEXIBLE</div>}<h2 style={{fontSize:34,margin:"5px 0"}}>{p.name}</h2><div style={{fontSize:24,fontWeight:800}}>{p.price}</div><p className="muted">{p.sub}</p></div><div style={{display:"grid",gap:9,flex:1}}>{p.features.map(f=><div key={f}>✓ {f}</div>)}</div><Link className="btn" style={{textAlign:"center"}} href={p.href}>{p.cta}</Link>{p.note&&<div className="muted" style={{textAlign:"center",fontSize:13}}>{p.note}</div>}</article>)}</section>
  <section className="section" style={{textAlign:"center"}}><div className="eyebrow">ANNUAL OPTION</div><h2>Save when you stay longer.</h2><p className="muted">Starter BND 80/year · Pro BND 180/year. Upgrades remain manual during V1; KADAI does not require an automatic subscription gateway yet.</p></section>
  <section className="card" style={{maxWidth:760,margin:"0 auto",textAlign:"center",padding:34}}><div className="eyebrow">KADAI</div><h2 style={{fontSize:34,margin:"8px 0"}}>Buka Kadai. Start Jual.</h2><p className="muted">Sell products, take appointments, manage capacity and keep customer conversations on WhatsApp.</p><Link className="btn" href="/signup">Buka Kadai</Link></section>
 </main>
}
